'use strict';

/**
 * Documentation tests: README, getting-started guide and generated API
 * reference are accurate, reachable and executable.
 *
 * - README links work on the npm package page even though the source
 *   repository may be private: every link is absolute (or an in-page anchor), and
 *   links to packaged documents point at files that are in the tarball.
 * - The getting-started guide's library and CLI examples are extracted
 *   verbatim and run against the *installed* package, with the real GitHub
 *   client talking HTTP to the fake GitHub in test/fixtures/composition (the
 *   example code is unchanged; only `fetch` is replaced by a preload). A retry
 *   with the same state path must not publish again, and the CLI example's
 *   outcome handling must report a blocked document.
 * - The API reference is generated by API Documenter from API Extractor's doc
 *   model (never hand-written), navigable (every relative link resolves), and
 *   the staleness check detects a declaration change that was not regenerated.
 *
 * @see https://api-extractor.com/pages/setup/generating_docs/
 * @see https://api-extractor.com/pages/setup/invoking/
 * @see https://docs.npmjs.com/cli/v11/configuring-npm/package-json#repository
 */

const test = require('node:test');
const { describe } = test;
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const { ROOT, packProject, installIntoConsumer } = require('./fixtures/package/installed-package.mts');
const { FakeHttpGitHub, REPOSITORY } = require('./fixtures/composition/fake-http-github.mts');
const { createGitWorld } = require('./fixtures/authoring-workflow/git-world.mts');

const README = fs.readFileSync(path.join(ROOT, 'README.md'), 'utf8');
const GUIDE_PATH = path.join(ROOT, 'docs', 'getting-started.md');
const GUIDE = fs.existsSync(GUIDE_PATH) ? fs.readFileSync(GUIDE_PATH, 'utf8') : '';
const API_DIR = path.join(ROOT, 'docs', 'api');
const PRELOAD = path.join(ROOT, 'test', 'fixtures', 'docs', 'fake-fetch-preload.mts');
const PACKAGE_DOCS_BASE = 'https://unpkg.com/sarif-to-comment/';

/** Every Markdown link target in `text` (inline links; code spans and fences excluded). */
function linkTargets(text) {
  const prose = text.replace(/```[\s\S]*?```/g, '').replace(/`[^`\n]*`/g, '');
  return [...prose.matchAll(/\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)].map((m) => m[1]);
}

/** The fenced code block that follows `<!-- verified-example: name -->`. */
function example(text, name) {
  const match = new RegExp(`<!-- verified-example: ${name} -->\\s*\\n\`\`\`(\\w+)\\n([\\s\\S]*?)\\n\`\`\``).exec(text);
  assert.ok(match, `the guide has a verified ${name} example`);
  return { language: match[1], code: match[2] };
}

describe('README', () => {
  test('every link works on the npm page even if the source repository is private (absolute or in-page)', () => {
    const targets = linkTargets(README);
    assert.ok(targets.length > 5);
    for (const target of targets) {
      assert.ok(/^https:\/\//.test(target) || target.startsWith('#'), `relative link would break on npm: ${target}`);
      assert.doesNotMatch(target, /github\.com\/mike-north\/sarif-to-comment/, `the source repository may be private: ${target}`);
    }
  });

  test('in-page anchors name real headings', () => {
    const slugs = new Set(
      [...README.matchAll(/^#{1,6} (.+)$/gm)].map((m) =>
        m[1].trim().toLowerCase().replace(/[^\w\- ]/g, '').replace(/ /g, '-'),
      ),
    );
    for (const target of linkTargets(README).filter((t) => t.startsWith('#'))) {
      assert.ok(slugs.has(target.slice(1)), `no heading for ${target}`);
    }
  });

  test('links to packaged documents point at files in the tarball', { skip: packProject().error || false }, () => {
    const files = new Set(packProject().result.files.map((f) => f.path));
    const packaged = linkTargets(README).filter((t) => t.startsWith(PACKAGE_DOCS_BASE));
    assert.ok(packaged.some((t) => t.endsWith('docs/getting-started.md')), 'README links the getting-started guide');
    assert.ok(packaged.some((t) => t.endsWith('docs/api/index.md')), 'README links the API reference');
    for (const target of packaged) {
      const file = target.slice(PACKAGE_DOCS_BASE.length).replace(/#.*$/, '');
      assert.ok(files.has(file), `${file} is linked but not packaged`);
    }
  });

  test('shows both surfaces and states the semantics consumers rely on', () => {
    assert.match(README, /```js[\s\S]*publishSarifReview/);
    assert.match(README, /```sh[\s\S]*sarif-to-comment[\s\\]*--sarif/);
    assert.match(README, /draft/i);
    assert.match(README, /one-way/i);
    assert.match(README, /GH_TOKEN/);
    assert.match(README, /trusted publishing/i);
  });
});

describe('getting-started guide', () => {
  test('exists, is linked from the README and covers what a first user needs', () => {
    assert.ok(GUIDE.length > 0, 'docs/getting-started.md exists');
    for (const topic of [
      /GH_TOKEN/,
      /personal access token/i,
      /reviewed commit/i,
      /source root|--source-root|sourceRootUri/i,
      /state path|--state/i,
      /do not delete/i,
      /uncertain/,
      /blocked/,
      /rejected/,
      /draft/i,
      /trusted publishing/i,
    ]) {
      assert.match(GUIDE, topic);
    }
  });

  test('its own links are absolute or point at other packaged documents', () => {
    for (const target of linkTargets(GUIDE)) {
      const ok =
        /^https:\/\//.test(target) ||
        target.startsWith('#') ||
        /^\.\/api\/[^/]+\.md$/.test(target) ||
        target === '../README.md';
      assert.ok(ok, `unexpected link ${target}`);
      if (target.startsWith('./api/')) assert.ok(fs.existsSync(path.join(ROOT, 'docs', target)), target);
    }
  });
});

describe('verified getting-started examples run against the installed package', () => {
  const skip = packProject().error || false;

  /** A fresh fake GitHub serving the composition repository, plus the example environment. */
  function world() {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'docs-example-'));
    const token = 'ghp_EXAMPLE_token_for_docs_tests_0123456789';
    FakeHttpGitHub.create(path.join(root, 'host'));
    const host = new FakeHttpGitHub(path.join(root, 'host'), token);
    const { owner, repo, pullNumber } = REPOSITORY.destination;
    const env = {
      PATH: process.env.PATH,
      HOME: root,
      GH_TOKEN: token,
      REVIEW_REPOSITORY: `${owner}/${repo}`,
      REVIEW_PULL: String(pullNumber),
      REVIEW_COMMIT: REPOSITORY.commits.head,
      REVIEW_STATE: path.join(root, 'review-state.json'),
      FAKE_HTTP_GITHUB_DIR: host.dir,
      NODE_OPTIONS: `--require=${PRELOAD}`,
    };
    return { root, host, env, token };
  }

  const createPosts = (host) => host.log().filter((r) => r.method === 'POST' && r.path.endsWith('/reviews')).length;

  test('the library example publishes one draft, and a retry does not publish again', { skip, timeout: 300_000 }, () => {
    const { consumer } = installIntoConsumer();
    const { language, code } = example(GUIDE, 'library');
    assert.equal(language, 'js');
    const file = path.join(consumer, 'publish-review.mjs');
    fs.writeFileSync(file, code);
    const { host, env, token } = world();

    const first = spawnSync(process.execPath, [file], { cwd: consumer, env, encoding: 'utf8', timeout: 60_000 });
    assert.equal(first.status, 0, first.stdout + first.stderr);
    const [stored] = host.reviews();
    assert.ok(stored, 'a review was created');
    assert.ok(first.stdout.includes(`#pullrequestreview-${stored.id}`), first.stdout);
    assert.equal(stored.request.commit_id, REPOSITORY.commits.head);
    assert.equal(Object.hasOwn(stored.request, 'event'), false, 'a draft');
    assert.ok(host.log().every((r) => r.authorized), 'the example authenticates with GH_TOKEN');
    assert.equal(first.stdout.includes(token) || first.stderr.includes(token), false);

    const again = spawnSync(process.execPath, [file], { cwd: consumer, env, encoding: 'utf8', timeout: 60_000 });
    assert.equal(again.status, 0, again.stdout + again.stderr);
    assert.equal(createPosts(host), 1, 'the retry with the same state path sent nothing');
  });

  test('the CLI example publishes from a SARIF file and reports each outcome', { skip, timeout: 300_000 }, () => {
    const { consumer } = installIntoConsumer();
    const { language, code } = example(GUIDE, 'cli');
    assert.equal(language, 'sh');
    const script = path.join(consumer, 'publish-review.sh');
    fs.writeFileSync(script, code);
    const { root, host, env } = world();
    fs.copyFileSync(path.join(ROOT, 'test', 'fixtures', 'composition', 'review.sarif.json'), path.join(consumer, 'results.sarif'));

    const published = spawnSync('bash', [script], { cwd: consumer, env, encoding: 'utf8', timeout: 120_000 });
    assert.equal(published.status, 0, published.stdout + published.stderr);
    assert.match(published.stdout, /pullrequestreview-\d+/);
    assert.equal(createPosts(host), 1);

    fs.writeFileSync(path.join(consumer, 'results.sarif'), JSON.stringify({ version: '2.1.0', runs: [{}] }));
    const blocked = spawnSync('bash', [script], {
      cwd: consumer,
      env: { ...env, REVIEW_STATE: path.join(root, 'other-state.json') },
      encoding: 'utf8',
      timeout: 120_000,
    });
    assert.equal(blocked.status, 2, blocked.stdout + blocked.stderr);
    assert.match(blocked.stdout + blocked.stderr, /blocked/i);
    assert.equal(createPosts(host), 1, 'a blocked document publishes nothing');
  });
});

describe('verified authoring examples run against the installed package in a real Git repository', () => {
  const skip = packProject().error || false;

  /**
   * The contract's worked example W1 (docs/second-milestone-contract-proposal.md
   * §7), written by hand: the reviewed src/parse.js, line 2 changed and staged,
   * and line 3 changed in the working tree only.
   */
  const STAGED_LINE = "  const parts = input === '' ? [] : input.split(',');\n";
  const W1 = {
    path: 'src/parse.js',
    base: "function parse(input) {\n  return input.split(',').map(Number);\n}\n",
    reviewed: "function parse(input) {\n  const parts = input.split(',');\n  return parts.map(Number);\n}\n",
    staged: `function parse(input) {\n${STAGED_LINE}  return parts.map(Number);\n}\n`,
    workingTree: `function parse(input) {\n${STAGED_LINE}  return UNSTAGED;\n}\n`,
  };
  const MESSAGE = 'Handle the empty-input case.';
  const DESTINATION = { owner: 'acme', repo: 'widgets', pullNumber: 42 };

  /** The W1 repository with the installed package available to it, a fake GitHub, and the example environment. */
  function world(label) {
    const { consumer } = installIntoConsumer();
    const git = createGitWorld(label, W1, DESTINATION);
    fs.symlinkSync(path.join(consumer, 'node_modules'), path.join(git.dir, 'node_modules'));
    const token = 'ghp_AUTHORING_EXAMPLE_token_0123456789';
    const hostDir = path.join(git.root, 'host');
    FakeHttpGitHub.create(hostDir, {}, git.repository);
    const host = new FakeHttpGitHub(hostDir, token);
    const env = {
      ...git.env,
      GH_TOKEN: token,
      REVIEW_REPOSITORY: `${DESTINATION.owner}/${DESTINATION.repo}`,
      REVIEW_PULL: String(DESTINATION.pullNumber),
      REVIEW_COMMIT: git.head,
      REVIEW_STATE: path.join(git.root, 'review-state.json'),
      FAKE_HTTP_GITHUB_DIR: hostDir,
      NODE_OPTIONS: `--require=${PRELOAD}`,
    };
    return { ...git, host, env, token };
  }

  /** One draft review with one suggestion on reviewed line 2 carrying `message`, and nothing unstaged. */
  function assertW1Review(w, message) {
    const reviews = w.host.reviews();
    assert.equal(reviews.length, 1);
    const [stored] = reviews;
    assert.equal(stored.state, 'PENDING');
    assert.equal(stored.request.commit_id, w.head);
    assert.equal(stored.request.comments.length, 1, JSON.stringify(stored.request.comments));
    const [comment] = stored.request.comments;
    assert.equal(comment.path, 'src/parse.js');
    assert.equal(comment.side, 'RIGHT');
    assert.equal(comment.line, 2);
    assert.ok(comment.body.includes(message), comment.body);
    assert.ok(comment.body.endsWith(`\`\`\`suggestion\n${STAGED_LINE}\`\`\``), comment.body);
    assert.ok(!JSON.stringify(stored).includes('UNSTAGED'), 'unstaged content never reaches GitHub');
    assert.ok(w.host.log().every((r) => r.authorized));
  }

  test('the CLI authoring example publishes the staged change as a suggestion on the finding', { skip, timeout: 300_000 }, () => {
    const { language, code } = example(GUIDE, 'authoring-cli');
    assert.equal(language, 'sh');
    const w = world('docs-authoring-cli');
    const script = path.join(w.root, 'authoring.sh');
    fs.writeFileSync(script, code);
    const result = spawnSync('bash', [script], { cwd: w.dir, env: w.env, encoding: 'utf8', timeout: 180_000 });
    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.ok(result.stdout.includes(MESSAGE), 'inspect shows the finding');
    assert.match(result.stdout, /pullrequestreview-\d+/);
    assert.ok(!(result.stdout + result.stderr).includes(w.token));
    assertW1Review(w, MESSAGE);
  });

  test('the library authoring example does the same in memory', { skip, timeout: 300_000 }, () => {
    const { language, code } = example(GUIDE, 'authoring-library');
    assert.equal(language, 'js');
    const w = world('docs-authoring-library');
    const file = path.join(w.dir, 'review.mjs');
    fs.writeFileSync(file, code);
    const result = spawnSync(process.execPath, [file], { cwd: w.dir, env: w.env, encoding: 'utf8', timeout: 180_000 });
    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.ok(result.stdout.includes(`/runs/0/results/0: ${MESSAGE} (1 fix)`), result.stdout);
    assertW1Review(w, MESSAGE);
  });

  test('the analyzer example adds staged changes to SARIF that was never initialized', { skip, timeout: 300_000 }, () => {
    const { language, code } = example(GUIDE, 'upstream-cli');
    assert.equal(language, 'sh');
    const w = world('docs-upstream-cli');
    const analyzerMessage = 'An empty input string yields one zero instead of no values.';
    fs.writeFileSync(
      path.join(w.dir, 'results.sarif'),
      JSON.stringify({
        version: '2.1.0',
        runs: [
          {
            tool: { driver: { name: 'example-linter', version: '1.0.0' } },
            results: [
              {
                ruleId: 'empty-input',
                level: 'warning',
                message: { text: analyzerMessage },
                locations: [{ physicalLocation: { artifactLocation: { uri: 'src/parse.js' }, region: { startLine: 2 } } }],
              },
            ],
          },
        ],
      }),
    );
    const script = path.join(w.root, 'upstream.sh');
    fs.writeFileSync(script, code);
    const result = spawnSync('bash', [script], { cwd: w.dir, env: w.env, encoding: 'utf8', timeout: 180_000 });
    assert.equal(result.status, 0, result.stdout + result.stderr);
    assertW1Review(w, analyzerMessage);
    assert.ok(w.host.reviews()[0].request.comments[0].body.includes('example-linter'), 'the analyzer stays credited');
  });
});

describe('the published outcome is described as a completed publication', () => {
  // A repeated call on a completed state record returns `published` without
  // contacting GitHub (test/publication.test.cjs, "a completed receipt is
  // final"). The review may since have been submitted, edited or deleted, so
  // no document may promise that it currently exists or is still a draft.
  // The shipped public declarations, generated from the TypeScript sources.
  const DECLARATIONS = fs.readFileSync(path.join(ROOT, 'dist', 'sarif-to-comment.d.ts'), 'utf8');
  const sources = {
    'dist/sarif-to-comment.d.ts': DECLARATIONS,
    'docs/getting-started.md': GUIDE,
    'README.md': README,
    ...Object.fromEntries(
      fs.existsSync(API_DIR)
        ? fs.readdirSync(API_DIR).map((p) => [`docs/api/${p}`, fs.readFileSync(path.join(API_DIR, p), 'utf8')])
        : [],
    ),
  };

  test('nothing claims the published review currently exists on GitHub', () => {
    for (const [name, text] of Object.entries(sources)) {
      assert.doesNotMatch(text, /review exists on GitHub/i, name);
    }
  });

  test('the declaration explains the receipt path and that the tool does not check again', () => {
    const doc = /\/\*\*((?:(?!\*\/)[\s\S])*?)\*\/\s*export declare interface IPublishedOutcome/.exec(DECLARATIONS);
    assert.ok(doc, 'IPublishedOutcome has a doc comment');
    assert.match(doc[1], /recorded as complete/i);
    assert.match(doc[1], /submitted, edited or deleted/i);
    assert.match(doc[1], /does not check/i);
  });

  test('the generated reference carries the same wording', () => {
    const page = sources['docs/api/sarif-to-comment.ipublishedoutcome.md'] || '';
    assert.match(page, /submitted, edited or deleted/i);
  });

  test('the getting-started outcome table does not assume the review is still a draft', () => {
    const row = GUIDE.split('\n').find((line) => line.startsWith('| `published` |'));
    assert.ok(row, 'the outcomes table has a published row');
    assert.match(row, /recorded as complete/i);
    assert.match(row, /submitted, edited or deleted/i);
    assert.doesNotMatch(row, /a person submits the draft/i);
  });
});

describe('release recovery instructions match the publish workflow', () => {
  // publish.yml runs only for pushes to main that change package.json, and a
  // GitHub Actions re-run executes the original run's commit and workflow. So
  // a re-run can only succeed when the cause was outside the repository
  // (registry outage, npm trusted-publisher settings, runner trouble); a fix
  // in the repository reaches the registry only through a later main commit
  // that changes package.json — normally the next Changesets patch release.
  const RELEASING = README.slice(README.indexOf('## Releasing'));
  const WORKFLOW = fs.readFileSync(path.join(ROOT, '.github', 'workflows', 'publish.yml'), 'utf8');

  test('the trigger contract the instructions rely on is unchanged', () => {
    assert.match(WORKFLOW, /^on:\n {2}push:\n {4}branches: \[main\]\n {4}paths:\n {6}- package\.json\n/m);
    assert.doesNotMatch(WORKFLOW, /workflow_dispatch/);
  });

  test('a re-run is only for causes outside the repository, and repeats the same commit', () => {
    assert.doesNotMatch(RELEASING, /re-run the workflow or push the fix/i);
    assert.match(RELEASING, /re-run[^.]*same commit/i);
    assert.match(RELEASING, /transient/i);
    assert.match(RELEASING, /trusted[- ]publisher settings/i);
  });

  test('a repository fix needs a new main commit that changes package.json, normally the next patch release', () => {
    assert.match(RELEASING, /does not start a publish run/i);
    assert.match(RELEASING, /changes `package\.json`/);
    assert.match(RELEASING, /patch/i);
    assert.match(RELEASING, /pnpm changeset/);
    assert.match(RELEASING, /pnpm run release:version/);
  });

  test('the first-release paragraph is procedural history, not a claim about the current tree', () => {
    const paragraph = RELEASING.split('\n').find((line) => line.startsWith('**First release.**'));
    assert.ok(paragraph, 'the Releasing section describes the first release');
    assert.match(paragraph, /0\.0\.0[^.]*baseline/i);
    assert.match(paragraph, /minor[^.]*0\.1\.0|0\.1\.0[^.]*minor/i);
    assert.doesNotMatch(paragraph, /is at `0\.0\.0`|pending changeset|\bremains?\b/i);
  });
});

describe('provenance and release-commit statements match what npm actually records', () => {
  // npm trusted publishing authenticates by OIDC from a private or a public
  // repository, but npm attaches a provenance attestation automatically only
  // when the source repository is public (https://docs.npmjs.com/trusted-publishers/).
  // Visibility is a repository setting the workflow never changes, so the docs
  // must be true for either setting: 0.1.0 was published from a public
  // repository and carries a verified attestation naming its commit
  // (docs/evidence/npm-release/provenance-statement.json), and a release from
  // a private repository carries none. The 0.1.0 tarball publish records no `gitHead`
  // in its registry metadata (docs/evidence/npm-release/registry-metadata.json),
  // so the release commit is identified by the workflow run and, when present,
  // the attestation.
  const RELEASING = README.slice(README.indexOf('## Releasing'));
  const PROVENANCE = RELEASING.split('\n').find((line) => line.startsWith('**Provenance.**')) || '';
  const LIMITATIONS = README.slice(README.indexOf('## Limitations'), README.indexOf('## Development'));
  const WORKFLOW = fs.readFileSync(path.join(ROOT, '.github', 'workflows', 'publish.yml'), 'utf8');

  test('the evidence the docs rely on: an attested 0.1.0 commit, and no gitHead in the registry metadata', () => {
    const statement = JSON.parse(fs.readFileSync(path.join(ROOT, 'docs/evidence/npm-release/provenance-statement.json'), 'utf8'));
    const [source] = statement.predicate.buildDefinition.resolvedDependencies;
    assert.equal(source.digest.gitCommit, '3797ca6efe2156d4c952fad7fed10b569f1dcbbb');
    assert.equal(statement.predicate.buildDefinition.externalParameters.workflow.path, '.github/workflows/publish.yml');
    const metadata = fs.readFileSync(path.join(ROOT, 'docs/evidence/npm-release/registry-metadata.json'), 'utf8');
    assert.doesNotMatch(metadata, /gitHead/);
  });

  test('no document claims every release lacks provenance or that the repository is (still) private', () => {
    for (const [name, text] of [['README.md', README], ['publish.yml', WORKFLOW]]) {
      assert.doesNotMatch(text, /(its|every|all) releases carry no (npm )?provenance/i, name);
      assert.doesNotMatch(text, /(the source|this) repository is private/i, name);
    }
  });

  test('the provenance paragraph is conditional on visibility, which the workflow never changes', () => {
    assert.match(PROVENANCE, /OIDC/);
    assert.match(PROVENANCE, /private or public|public or private/i);
    assert.match(PROVENANCE, /only when the source repository is public/i);
    assert.match(PROVENANCE, /private repository[^.]*no provenance|no provenance[^.]*private repository/i);
    assert.match(PROVENANCE, /never changes[^.]*visibility|visibility[^.]*never changes/i);
    assert.match(PROVENANCE, /0\.1\.0[^.]*(attestation|provenance)/i);
    assert.match(PROVENANCE, /--provenance/);
  });

  test('the limitations state the private-repository provenance limitation conditionally', () => {
    const bullet = LIMITATIONS.split('\n').find((line) => /provenance/i.test(line)) || '';
    assert.match(bullet, /private/i);
    assert.match(bullet, /public/i);
    assert.match(bullet, /\bwhen\b|\bif\b/i);
  });

  test('the release commit is identified without assuming npm records gitHead', () => {
    assert.doesNotMatch(RELEASING, /npm records the published commit/i);
    assert.match(RELEASING, /no `gitHead`|not record[^.]*`gitHead`|without[^.]*`gitHead`/i);
    assert.match(RELEASING, /workflow run/i);
    assert.match(RELEASING, /pnpm changeset git-tag/);
  });

  test('the workflow comment is conditional too, and the workflow still never forces provenance', () => {
    assert.match(WORKFLOW, /^# Provenance:[\s\S]*?public[\s\S]*?private/m);
    assert.doesNotMatch(WORKFLOW.replace(/^#.*$/gm, ''), /--provenance|NPM_CONFIG_PROVENANCE/i);
  });
});

describe('release tooling comments are accurate and durable', () => {
  const GUARD_TEXT = fs.readFileSync(path.join(ROOT, 'scripts', 'release-guard.cjs'), 'utf8');
  const RELEASE_TESTS = fs.readFileSync(path.join(ROOT, 'test', 'release.test.cjs'), 'utf8');

  test('plans are described as the sandboxed `changeset version` result, not `changeset status --output`', () => {
    for (const [name, text] of [['scripts/release-guard.cjs', GUARD_TEXT], ['test/release.test.cjs', RELEASE_TESTS]]) {
      assert.doesNotMatch(text, /(written by|A) `changeset status --output`/, name);
    }
    assert.match(GUARD_TEXT, /`plan` is the result of computeReleasePlan/);
  });

  test('code comments and test names carry no task-specific review labels', () => {
    // Owned sources in every language they are written in, so the scan keeps
    // covering them as JavaScript is converted to TypeScript.
    const scanned = ['scripts', 'test', 'src'].map((dir) => [
      dir,
      fs
        .readdirSync(path.join(ROOT, dir))
        .filter((f) => /\.([cm]?js|[cm]?ts)$/.test(f))
        .map((f) => path.join(dir, f)),
    ]);
    for (const [dir, found] of scanned) assert.ok(found.length > 0, `the scan finds sources in ${dir}/`);
    const files = scanned.flatMap(([, found]) => found);
    assert.ok(files.some((f) => /^scripts\/.*\.mts$/.test(f)), 'the scan covers TypeScript tooling');
    // Built from fragments so this file does not contain the labels it forbids.
    const label = new RegExp(['rev' + 'iew V\\d', '\\(V' + '\\d\\)'].join('|'));
    for (const file of files) {
      assert.doesNotMatch(fs.readFileSync(path.join(ROOT, file), 'utf8'), label, file);
    }
  });
});

describe('generated API reference', () => {
  const pages = fs.existsSync(API_DIR) ? fs.readdirSync(API_DIR).filter((f) => f.endsWith('.md')) : [];

  test('is generated by API Documenter, not hand-written', () => {
    assert.ok(pages.includes('index.md') && pages.length >= 3, `pages: ${pages}`);
    for (const page of pages) {
      assert.match(
        fs.readFileSync(path.join(API_DIR, page), 'utf8'),
        /^<!-- Do not edit this file\. It is automatically generated by API Documenter\. -->/,
        page,
      );
    }
  });

  test('is navigable: every relative link resolves to a generated page', () => {
    for (const page of pages) {
      for (const target of linkTargets(fs.readFileSync(path.join(API_DIR, page), 'utf8'))) {
        if (/^https?:|^#/.test(target)) continue;
        assert.ok(fs.existsSync(path.join(API_DIR, target.replace(/#.*$/, ''))), `${page} links missing ${target}`);
      }
    }
  });

  test('documents the public API and its input/outcome types', () => {
    const all = pages.map((p) => fs.readFileSync(path.join(API_DIR, p), 'utf8')).join('\n');
    for (const name of ['publishSarifReview', 'IPublishSarifReviewInput', 'PublishSarifReviewOutcome', 'IPublishedOutcome']) {
      assert.ok(all.includes(name), `${name} is documented`);
    }
  });

  test('the API report is committed for review', () => {
    const report = fs.readFileSync(path.join(ROOT, 'api-report', 'sarif-to-comment.api.md'), 'utf8');
    assert.match(report, /export function publishSarifReview\(/);
  });

  test('the staleness check passes for this checkout and detects an unregenerated declaration change', { timeout: 300_000 }, () => {
    const copy = fs.mkdtempSync(path.join(os.tmpdir(), 'api-docs-'));
    for (const entry of ['package.json', 'api-extractor.json', 'tsconfig.json', 'tsconfig.base.json', 'src', 'dist', 'api-report', 'docs/api', 'scripts']) {
      fs.cpSync(path.join(ROOT, entry), path.join(copy, entry), { recursive: true });
    }
    fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(copy, 'node_modules'), 'dir');
    const check = () => spawnSync(process.execPath, ['scripts/api-docs.cjs', 'check'], { cwd: copy, encoding: 'utf8', timeout: 240_000 });

    const fresh = check();
    assert.equal(fresh.status, 0, fresh.stdout + fresh.stderr);

    // A documentation change compiled into the declarations but never
    // regenerated into the report and reference.
    const declarations = path.join(copy, 'dist', 'publish-sarif-review.d.cts');
    const text = fs.readFileSync(declarations, 'utf8');
    const changed = text.replace(/(\n \* @public\n \*\/\nexport declare function publishSarifReview)/, '\n *\n * A sentence added without regenerating the docs.$1');
    assert.notEqual(changed, text, 'control: the declaration was changed');
    fs.writeFileSync(declarations, changed);
    const stale = check();
    assert.equal(stale.status, 1, stale.stdout + stale.stderr);
    assert.match(stale.stdout + stale.stderr, /docs\/api|api-report/);
  });
});
